### PR TITLE
Redirect the user based on their login status

### LINKED ISSUE #48: Home page is empty
I used LectureChat yesterday, and today I just navigated to https://lecturechat.ew.r.appspot.com/home-page.html. The page was empty. I could still see Sign Out button.

events-script.js:417 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at loadEvents (events-script.js:417)
    at async createCalendarOfTheMonth (events-script.js:270)
home-page.html:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input

### PR DESCRIPTION
**Pull request by AlexandraImbrisca**
This pull request solves the problem of **users accessing the home page without being logged in** (related to the #48).

Now if the user is not logged in and tries to access the home page, this page will be empty and the content is not loaded. The change introduced consists of a **redirection to the start page if the user is not logged in**.

- The AddUserServlet.java will contain a GET method that can be used to check if the cookie is already set up correctly (the **id_token** is **present** and it is **valid** - usually id_tokens expire in ~10 hours).
- The profile will be loaded only if the user is logged in. Otherwise, they are redirected to the start page.
- The functions related to the authentication process were separated in a new file authentication.js with changes only for loadProfileData, signOut.
- The function getLoginStatus was introduced to check if the cookie is already set up correctly and the user is logged in the AuthInstance (the second condition was needed for **loading the profile data linked with their Google account**).

### CODE REVIEW

**Review by tatiana-s — APPROVED** [review]

File: src/main/webapp/home-page-script.js [hunk 1]
```diff
@@ -40,7 +41,13 @@ function loadHomeClient() {
  * Loads the data associated with the user profile.
  */
 async function loadProfile() {
-  await loadProfileData();
+  const loginStatus = await getLoginStatus();
+  if (!loginStatus) {
+    window.location.href = 'index.html';
```
Comment (csperl) [inline src/main/webapp/home-page-script.js:46]: You do a client side redirect here. That means that the JS code in the browser checks if the user is logged in and redirects if not. However, that could be done on the server side as well.

File: src/main/java/com/google/lecturechat/servlets/AddUserServlet.java [hunk 2]
```diff
@@ -38,16 +36,35 @@ public void init() {
...
+    String name = (String) userPayload.get("name");
+    datastore.addUser(userId, name);
+  }
+
   @Override
   public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
     Optional<Payload> userPayload = AuthStatus.getUserPayload(request);
 
     if (!userPayload.isPresent()) {
+      response.sendRedirect(request.getContextPath() + "/index.html");
```
Comment (csperl) [inline src/main/java/com/google/lecturechat/servlets/AddUserServlet.java:50]: This is a server side redirect. That means, the server detects that the user is not logged in and therefore redirects to the start page. You could add that in all other pages as well.

On the start page you also check if the user is already logged in (if there is a cookie, etc.) If that is the case, then you return with a redirect to the homepage.

**Review by csperl — COMMENTED** [review]
I think it would be simpler to just return a response with a redirect to the start page if the user is not logged in. See my comments.

Given that this is a completely different approach, feel free to leave this pull request as is and try it out in a new branch first.
